Release of vSRX 20.4R3-S2.6
ibm-cloud-docs/vsrx pull request #9
Opened 2022-03-23 21:35 UTC by bdumler

Updating the IBM docs to include information for the release of vSRX 20.4R3-S2.2

2022-03-23 22:36 UTC, slomes commented
Release date should be 2022 not 2021

2022-03-23 22:37 UTC, slomes requested changes

2022-03-23 22:37 UTC, slomes commented on vsrx-version-notes.md
> +| 20.4R3-S2 | 20.4R3-S2.6 | March 24, 2021 | [More information](https://kb.juniper.net/InfoCenter/index?page=content&id=TSB18293){: external} |
Release on March 24, 2022 not 2021.

2022-03-24 12:37 UTC, bdumler commented
Incorrect and needs updating so closing to make change in correct repo.

2022-03-24 12:37 UTC, closed without merging